### ISSUE TITLE
how to guide is needed

### ISSUE THREAD

**Issue by DegaZZZ** [DarkLord76865/Autofish-Fishing-Planet#5] opened 2023-07-05 14:10 UTC
Application doesn't seem to work unless there is some weird way of launching it that is not explained. tried both - building it myself and prebuilt version, just doesnt work.

**Comment by DarkLord76865** [comment] 2023-07-06 12:30
Hi,
application should work without any additional setup, therefore I don't think that how to guide is needed. What you are saying seems very strange, can you give me more information about your system? Windows version for example. (If you don't use Windows, I don't know whether this app would work). Application should work just by double clicking/launching it. What Python version did you use for building it yourself? I'm happy to try to help you, but I need more information on what exactly is happening. It may even be that app gets blocked by your antivirus? 

Regards

**Comment by DarkLord76865** [comment] 2023-07-24 10:07
Since I didn't get any additional feedback, I'm assuming the problem is solved and I'm closing this issue.

**Closed by DarkLord76865** 2023-07-24 10:07 UTC
Labels: bug
